2024-09-27 12:18:16,994 INFO    StreamThr :55280 [internal.py:wandb_internal():85] W&B internal server running at pid: 55280, started at: 2024-09-27 12:18:16.992938
2024-09-27 12:18:16,996 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: status
2024-09-27 12:18:17,000 INFO    WriterThread:55280 [datastore.py:open_for_write():87] open: /Users/baeyeongmin/Desktop/workspace/dacon-2024-gbt-hackerton/wandb/run-20240927_121816-5tr1q16q/run-5tr1q16q.wandb
2024-09-27 12:18:17,000 DEBUG   SenderThread:55280 [sender.py:send():379] send: header
2024-09-27 12:18:17,030 DEBUG   SenderThread:55280 [sender.py:send():379] send: run
2024-09-27 12:18:17,614 INFO    SenderThread:55280 [dir_watcher.py:__init__():211] watching files in: /Users/baeyeongmin/Desktop/workspace/dacon-2024-gbt-hackerton/wandb/run-20240927_121816-5tr1q16q/files
2024-09-27 12:18:17,614 INFO    SenderThread:55280 [sender.py:_start_run_threads():1188] run started: 5tr1q16q with start time 1727407096.993301
2024-09-27 12:18:17,626 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: check_version
2024-09-27 12:18:17,626 DEBUG   SenderThread:55280 [sender.py:send_request():406] send_request: check_version
2024-09-27 12:18:17,702 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: run_start
2024-09-27 12:18:17,711 DEBUG   HandlerThread:55280 [system_info.py:__init__():26] System info init
2024-09-27 12:18:17,711 DEBUG   HandlerThread:55280 [system_info.py:__init__():41] System info init done
2024-09-27 12:18:17,711 INFO    HandlerThread:55280 [system_monitor.py:start():194] Starting system monitor
2024-09-27 12:18:17,711 INFO    SystemMonitor:55280 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-09-27 12:18:17,711 INFO    HandlerThread:55280 [system_monitor.py:probe():214] Collecting system info
2024-09-27 12:18:17,715 INFO    SystemMonitor:55280 [interfaces.py:start():188] Started cpu monitoring
2024-09-27 12:18:17,719 ERROR   HandlerThread:55280 [gpu_apple.py:probe():176] GPU stats error: [Errno 2] No such file or directory: '/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 164, in probe
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats'
2024-09-27 12:18:17,720 INFO    SystemMonitor:55280 [interfaces.py:start():188] Started disk monitoring
2024-09-27 12:18:17,722 DEBUG   HandlerThread:55280 [system_info.py:probe():152] Probing system
2024-09-27 12:18:17,722 INFO    SystemMonitor:55280 [interfaces.py:start():188] Started gpuapple monitoring
2024-09-27 12:18:17,726 INFO    SystemMonitor:55280 [interfaces.py:start():188] Started memory monitoring
2024-09-27 12:18:17,726 ERROR   gpuapple  :55280 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats'
2024-09-27 12:18:17,727 INFO    SystemMonitor:55280 [interfaces.py:start():188] Started network monitoring
2024-09-27 12:18:17,731 DEBUG   HandlerThread:55280 [system_info.py:_probe_git():137] Probing git
2024-09-27 12:18:17,749 DEBUG   HandlerThread:55280 [system_info.py:_probe_git():145] Probing git done
2024-09-27 12:18:17,749 DEBUG   HandlerThread:55280 [system_info.py:probe():200] Probing system done
2024-09-27 12:18:17,749 DEBUG   HandlerThread:55280 [system_monitor.py:probe():223] {'os': 'macOS-14.2.1-arm64-arm-64bit', 'python': '3.11.9', 'heartbeatAt': '2024-09-27T03:18:17.724746', 'startedAt': '2024-09-27T03:18:16.978708', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '/Users/baeyeongmin/Desktop/workspace/dacon-2024-gbt-hackerton/run.py', 'codePathLocal': 'run.py', 'codePath': 'run.py', 'git': {'remote': 'https://github.com/bohblue2/dacon-2024-gbt-hackerton', 'commit': '4b0cc3b6eecebd7a967b7c82a67240aeee13a238'}, 'email': 'brian.bae.contact@gmail.com', 'root': '/Users/baeyeongmin/Desktop/workspace/dacon-2024-gbt-hackerton', 'host': 'baeyeongmin-ui-MacBookAir.local', 'username': 'baeyeongmin', 'executable': '/Users/baeyeongmin/micromamba/envs/enigma_mdms/bin/python', 'cpu_count': 8, 'cpu_count_logical': 8, 'cpu_freq': {'current': 3504, 'min': 600, 'max': 3504}, 'cpu_freq_per_core': [{'current': 3504, 'min': 600, 'max': 3504}], 'disk': {'/': {'total': 228.27386474609375, 'used': 204.86547088623047}}, 'gpuapple': {'type': 'arm', 'vendor': 'Apple'}, 'memory': {'total': 16.0}}
2024-09-27 12:18:17,749 INFO    HandlerThread:55280 [system_monitor.py:probe():224] Finished collecting system info
2024-09-27 12:18:17,749 INFO    HandlerThread:55280 [system_monitor.py:probe():227] Publishing system info
2024-09-27 12:18:17,749 DEBUG   HandlerThread:55280 [system_info.py:_save_conda():209] Saving list of conda packages installed into the current environment
2024-09-27 12:18:18,616 INFO    Thread-12 :55280 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/baeyeongmin/Desktop/workspace/dacon-2024-gbt-hackerton/wandb/run-20240927_121816-5tr1q16q/files/conda-environment.yaml
2024-09-27 12:18:19,733 ERROR   gpuapple  :55280 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats'
2024-09-27 12:18:21,111 DEBUG   HandlerThread:55280 [system_info.py:_save_conda():224] Saving conda packages done
2024-09-27 12:18:21,112 INFO    HandlerThread:55280 [system_monitor.py:probe():229] Finished publishing system info
2024-09-27 12:18:21,115 DEBUG   SenderThread:55280 [sender.py:send():379] send: files
2024-09-27 12:18:21,116 INFO    SenderThread:55280 [sender.py:_save_file():1454] saving file wandb-metadata.json with policy now
2024-09-27 12:18:21,270 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: python_packages
2024-09-27 12:18:21,270 DEBUG   SenderThread:55280 [sender.py:send_request():406] send_request: python_packages
2024-09-27 12:18:21,270 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-27 12:18:21,271 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: stop_status
2024-09-27 12:18:21,271 DEBUG   SenderThread:55280 [sender.py:send_request():406] send_request: stop_status
2024-09-27 12:18:21,627 INFO    Thread-12 :55280 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/baeyeongmin/Desktop/workspace/dacon-2024-gbt-hackerton/wandb/run-20240927_121816-5tr1q16q/files/conda-environment.yaml
2024-09-27 12:18:21,627 INFO    Thread-12 :55280 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/baeyeongmin/Desktop/workspace/dacon-2024-gbt-hackerton/wandb/run-20240927_121816-5tr1q16q/files/requirements.txt
2024-09-27 12:18:21,627 INFO    Thread-12 :55280 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/baeyeongmin/Desktop/workspace/dacon-2024-gbt-hackerton/wandb/run-20240927_121816-5tr1q16q/files/wandb-metadata.json
2024-09-27 12:18:21,692 DEBUG   SenderThread:55280 [sender.py:send():379] send: telemetry
2024-09-27 12:18:21,739 ERROR   gpuapple  :55280 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats'
2024-09-27 12:18:22,275 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-27 12:18:22,698 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: status_report
2024-09-27 12:18:22,741 INFO    wandb-upload_0:55280 [upload_job.py:push():130] Uploaded file /var/folders/4x/krzx13nx7xq26hm5m_1wrp3h0000gn/T/tmpc19_d7iawandb/f5qi90uq-wandb-metadata.json
2024-09-27 12:18:23,321 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-27 12:18:23,744 ERROR   gpuapple  :55280 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats'
2024-09-27 12:18:24,290 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-27 12:18:25,292 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-27 12:18:25,758 ERROR   gpuapple  :55280 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats'
2024-09-27 12:18:26,292 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-27 12:18:26,651 INFO    Thread-12 :55280 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/baeyeongmin/Desktop/workspace/dacon-2024-gbt-hackerton/wandb/run-20240927_121816-5tr1q16q/files/output.log
2024-09-27 12:18:27,294 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-27 12:18:27,768 ERROR   gpuapple  :55280 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats'
2024-09-27 12:18:28,310 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-27 12:18:28,310 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: status_report
2024-09-27 12:18:28,659 INFO    Thread-12 :55280 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/baeyeongmin/Desktop/workspace/dacon-2024-gbt-hackerton/wandb/run-20240927_121816-5tr1q16q/files/output.log
2024-09-27 12:18:29,305 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-27 12:18:29,781 ERROR   gpuapple  :55280 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats'
2024-09-27 12:18:30,325 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-27 12:18:31,311 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-27 12:18:31,792 ERROR   gpuapple  :55280 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats'
2024-09-27 12:18:32,348 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-27 12:18:33,338 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: status_report
2024-09-27 12:18:33,339 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-27 12:18:33,812 ERROR   gpuapple  :55280 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats'
2024-09-27 12:18:34,343 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-27 12:18:35,348 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-27 12:18:35,821 ERROR   gpuapple  :55280 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats'
2024-09-27 12:18:36,277 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: stop_status
2024-09-27 12:18:36,278 DEBUG   SenderThread:55280 [sender.py:send_request():406] send_request: stop_status
2024-09-27 12:18:36,352 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-27 12:18:37,357 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-27 12:18:37,831 ERROR   gpuapple  :55280 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats'
2024-09-27 12:18:38,359 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-27 12:18:38,592 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: status_report
2024-09-27 12:18:39,361 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-27 12:18:39,840 ERROR   gpuapple  :55280 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats'
2024-09-27 12:18:40,382 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-27 12:18:41,374 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-27 12:18:41,847 ERROR   gpuapple  :55280 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats'
2024-09-27 12:18:42,376 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-27 12:18:43,382 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-27 12:18:43,862 ERROR   gpuapple  :55280 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats'
2024-09-27 12:18:44,330 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: status_report
2024-09-27 12:18:44,386 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-27 12:18:45,412 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-27 12:18:45,872 ERROR   gpuapple  :55280 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats'
2024-09-27 12:18:46,401 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-27 12:18:47,419 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-27 12:18:47,912 ERROR   gpuapple  :55280 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats'
2024-09-27 12:18:48,413 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-27 12:18:49,349 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: status_report
2024-09-27 12:18:49,415 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-27 12:18:50,480 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-27 12:18:50,502 ERROR   gpuapple  :55280 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats'
2024-09-27 12:18:50,828 INFO    Thread-12 :55280 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/baeyeongmin/Desktop/workspace/dacon-2024-gbt-hackerton/wandb/run-20240927_121816-5tr1q16q/files/config.yaml
2024-09-27 12:18:51,287 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: stop_status
2024-09-27 12:18:51,288 DEBUG   SenderThread:55280 [sender.py:send_request():406] send_request: stop_status
2024-09-27 12:18:51,423 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-27 12:18:52,431 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-27 12:18:52,519 ERROR   gpuapple  :55280 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats'
2024-09-27 12:18:53,438 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-27 12:18:54,450 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-27 12:18:54,534 ERROR   gpuapple  :55280 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats'
2024-09-27 12:18:55,833 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-27 12:18:56,596 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: status_report
2024-09-27 12:18:57,010 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-27 12:18:57,084 ERROR   gpuapple  :55280 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats'
2024-09-27 12:18:57,606 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-27 12:18:59,113 ERROR   gpuapple  :55280 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats'
2024-09-27 12:18:59,116 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-27 12:18:59,862 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-27 12:19:00,861 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-27 12:19:01,119 ERROR   gpuapple  :55280 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/baeyeongmin/micromamba/envs/enigma_mdms/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats'
2024-09-27 12:19:01,900 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-27 12:19:02,411 DEBUG   SenderThread:55280 [sender.py:send():379] send: exit
2024-09-27 12:19:02,417 INFO    SenderThread:55280 [sender.py:send_exit():586] handling exit code: 255
2024-09-27 12:19:02,439 INFO    SenderThread:55280 [sender.py:send_exit():588] handling runtime: 44
2024-09-27 12:19:02,439 INFO    SenderThread:55280 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-09-27 12:19:02,459 INFO    SenderThread:55280 [sender.py:send_exit():594] send defer
2024-09-27 12:19:02,460 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: defer
2024-09-27 12:19:02,466 INFO    HandlerThread:55280 [handler.py:handle_request_defer():184] handle defer: 0
2024-09-27 12:19:02,466 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: status_report
2024-09-27 12:19:02,466 DEBUG   SenderThread:55280 [sender.py:send_request():406] send_request: defer
2024-09-27 12:19:02,467 INFO    SenderThread:55280 [sender.py:send_request_defer():610] handle sender defer: 0
2024-09-27 12:19:02,467 INFO    SenderThread:55280 [sender.py:transition_state():614] send defer: 1
2024-09-27 12:19:02,467 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: defer
2024-09-27 12:19:02,467 INFO    HandlerThread:55280 [handler.py:handle_request_defer():184] handle defer: 1
2024-09-27 12:19:02,467 DEBUG   SenderThread:55280 [sender.py:send_request():406] send_request: defer
2024-09-27 12:19:02,467 INFO    SenderThread:55280 [sender.py:send_request_defer():610] handle sender defer: 1
2024-09-27 12:19:02,467 INFO    SenderThread:55280 [sender.py:transition_state():614] send defer: 2
2024-09-27 12:19:02,467 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: defer
2024-09-27 12:19:02,467 INFO    HandlerThread:55280 [handler.py:handle_request_defer():184] handle defer: 2
2024-09-27 12:19:02,473 INFO    HandlerThread:55280 [system_monitor.py:finish():203] Stopping system monitor
2024-09-27 12:19:02,480 DEBUG   SystemMonitor:55280 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-09-27 12:19:02,480 INFO    HandlerThread:55280 [interfaces.py:finish():200] Joined cpu monitor
2024-09-27 12:19:02,480 DEBUG   SystemMonitor:55280 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-09-27 12:19:02,480 DEBUG   SystemMonitor:55280 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-09-27 12:19:02,480 INFO    HandlerThread:55280 [interfaces.py:finish():200] Joined disk monitor
2024-09-27 12:19:02,487 INFO    HandlerThread:55280 [interfaces.py:finish():200] Joined gpuapple monitor
2024-09-27 12:19:02,487 INFO    HandlerThread:55280 [interfaces.py:finish():200] Joined memory monitor
2024-09-27 12:19:02,488 INFO    HandlerThread:55280 [interfaces.py:finish():200] Joined network monitor
2024-09-27 12:19:02,597 DEBUG   SenderThread:55280 [sender.py:send_request():406] send_request: defer
2024-09-27 12:19:02,597 INFO    SenderThread:55280 [sender.py:send_request_defer():610] handle sender defer: 2
2024-09-27 12:19:02,597 INFO    SenderThread:55280 [sender.py:transition_state():614] send defer: 3
2024-09-27 12:19:02,597 DEBUG   SenderThread:55280 [sender.py:send():379] send: telemetry
2024-09-27 12:19:02,598 DEBUG   SenderThread:55280 [sender.py:send():379] send: stats
2024-09-27 12:19:02,604 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: defer
2024-09-27 12:19:02,604 INFO    HandlerThread:55280 [handler.py:handle_request_defer():184] handle defer: 3
2024-09-27 12:19:02,605 DEBUG   SenderThread:55280 [sender.py:send_request():406] send_request: defer
2024-09-27 12:19:02,605 INFO    SenderThread:55280 [sender.py:send_request_defer():610] handle sender defer: 3
2024-09-27 12:19:02,605 INFO    SenderThread:55280 [sender.py:transition_state():614] send defer: 4
2024-09-27 12:19:02,605 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: defer
2024-09-27 12:19:02,605 INFO    HandlerThread:55280 [handler.py:handle_request_defer():184] handle defer: 4
2024-09-27 12:19:02,605 DEBUG   SenderThread:55280 [sender.py:send_request():406] send_request: defer
2024-09-27 12:19:02,605 INFO    SenderThread:55280 [sender.py:send_request_defer():610] handle sender defer: 4
2024-09-27 12:19:02,605 INFO    SenderThread:55280 [sender.py:transition_state():614] send defer: 5
2024-09-27 12:19:02,605 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: defer
2024-09-27 12:19:02,605 INFO    HandlerThread:55280 [handler.py:handle_request_defer():184] handle defer: 5
2024-09-27 12:19:02,605 DEBUG   SenderThread:55280 [sender.py:send():379] send: summary
2024-09-27 12:19:02,605 INFO    SenderThread:55280 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-09-27 12:19:02,605 DEBUG   SenderThread:55280 [sender.py:send_request():406] send_request: defer
2024-09-27 12:19:02,605 INFO    SenderThread:55280 [sender.py:send_request_defer():610] handle sender defer: 5
2024-09-27 12:19:02,605 INFO    SenderThread:55280 [sender.py:transition_state():614] send defer: 6
2024-09-27 12:19:02,605 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: defer
2024-09-27 12:19:02,605 INFO    HandlerThread:55280 [handler.py:handle_request_defer():184] handle defer: 6
2024-09-27 12:19:02,605 DEBUG   SenderThread:55280 [sender.py:send_request():406] send_request: defer
2024-09-27 12:19:02,605 INFO    SenderThread:55280 [sender.py:send_request_defer():610] handle sender defer: 6
2024-09-27 12:19:02,607 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: status_report
2024-09-27 12:19:02,907 INFO    Thread-12 :55280 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/baeyeongmin/Desktop/workspace/dacon-2024-gbt-hackerton/wandb/run-20240927_121816-5tr1q16q/files/output.log
2024-09-27 12:19:02,908 INFO    Thread-12 :55280 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/baeyeongmin/Desktop/workspace/dacon-2024-gbt-hackerton/wandb/run-20240927_121816-5tr1q16q/files/wandb-summary.json
2024-09-27 12:19:02,921 INFO    SenderThread:55280 [sender.py:transition_state():614] send defer: 7
2024-09-27 12:19:02,921 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: defer
2024-09-27 12:19:02,921 INFO    HandlerThread:55280 [handler.py:handle_request_defer():184] handle defer: 7
2024-09-27 12:19:02,922 DEBUG   SenderThread:55280 [sender.py:send_request():406] send_request: defer
2024-09-27 12:19:02,922 INFO    SenderThread:55280 [sender.py:send_request_defer():610] handle sender defer: 7
2024-09-27 12:19:03,417 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: poll_exit
2024-09-27 12:19:03,913 INFO    Thread-12 :55280 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/baeyeongmin/Desktop/workspace/dacon-2024-gbt-hackerton/wandb/run-20240927_121816-5tr1q16q/files/config.yaml
2024-09-27 12:19:04,611 INFO    SenderThread:55280 [sender.py:transition_state():614] send defer: 8
2024-09-27 12:19:04,612 DEBUG   SenderThread:55280 [sender.py:send_request():406] send_request: poll_exit
2024-09-27 12:19:04,612 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: defer
2024-09-27 12:19:04,612 INFO    HandlerThread:55280 [handler.py:handle_request_defer():184] handle defer: 8
2024-09-27 12:19:04,613 DEBUG   SenderThread:55280 [sender.py:send_request():406] send_request: defer
2024-09-27 12:19:04,613 INFO    SenderThread:55280 [sender.py:send_request_defer():610] handle sender defer: 8
2024-09-27 12:19:04,613 INFO    SenderThread:55280 [job_builder.py:build():440] Attempting to build job artifact
2024-09-27 12:19:04,651 INFO    SenderThread:55280 [job_builder.py:_get_source_type():569] is repo sourced job
2024-09-27 12:19:04,916 INFO    Thread-12 :55280 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/baeyeongmin/Desktop/workspace/dacon-2024-gbt-hackerton/wandb/run-20240927_121816-5tr1q16q/files/output.log
2024-09-27 12:19:05,428 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: poll_exit
2024-09-27 12:19:06,482 INFO    SenderThread:55280 [job_builder.py:build():545] adding wandb-job metadata file
2024-09-27 12:19:07,193 INFO    SenderThread:55280 [sender.py:transition_state():614] send defer: 9
2024-09-27 12:19:07,193 DEBUG   SenderThread:55280 [sender.py:send_request():406] send_request: poll_exit
2024-09-27 12:19:07,193 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: defer
2024-09-27 12:19:07,193 DEBUG   SenderThread:55280 [sender.py:send():379] send: artifact
2024-09-27 12:19:07,193 INFO    HandlerThread:55280 [handler.py:handle_request_defer():184] handle defer: 9
2024-09-27 12:19:07,457 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: poll_exit
2024-09-27 12:19:08,561 INFO    SenderThread:55280 [sender.py:send_artifact():1530] sent artifact job-https___github.com_bohblue2_dacon-2024-gbt-hackerton_run.py - {'id': 'QXJ0aWZhY3Q6MTI1MDE5Nzg1OQ==', 'state': 'COMMITTED', 'artifactSequence': {'id': 'QXJ0aWZhY3RDb2xsZWN0aW9uOjQ2Mjg0OTQ3OQ==', 'latestArtifact': {'id': 'QXJ0aWZhY3Q6MTI1MDE5Nzg1OQ==', 'versionIndex': 0}}}
2024-09-27 12:19:08,561 DEBUG   SenderThread:55280 [sender.py:send_request():406] send_request: defer
2024-09-27 12:19:08,561 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: status_report
2024-09-27 12:19:08,561 INFO    SenderThread:55280 [sender.py:send_request_defer():610] handle sender defer: 9
2024-09-27 12:19:08,562 INFO    SenderThread:55280 [dir_watcher.py:finish():358] shutting down directory watcher
2024-09-27 12:19:09,263 INFO    SenderThread:55280 [dir_watcher.py:finish():388] scan: /Users/baeyeongmin/Desktop/workspace/dacon-2024-gbt-hackerton/wandb/run-20240927_121816-5tr1q16q/files
2024-09-27 12:19:09,263 INFO    SenderThread:55280 [dir_watcher.py:finish():402] scan save: /Users/baeyeongmin/Desktop/workspace/dacon-2024-gbt-hackerton/wandb/run-20240927_121816-5tr1q16q/files/requirements.txt requirements.txt
2024-09-27 12:19:09,264 INFO    SenderThread:55280 [dir_watcher.py:finish():402] scan save: /Users/baeyeongmin/Desktop/workspace/dacon-2024-gbt-hackerton/wandb/run-20240927_121816-5tr1q16q/files/output.log output.log
2024-09-27 12:19:10,131 INFO    SenderThread:55280 [dir_watcher.py:finish():402] scan save: /Users/baeyeongmin/Desktop/workspace/dacon-2024-gbt-hackerton/wandb/run-20240927_121816-5tr1q16q/files/config.yaml config.yaml
2024-09-27 12:19:10,132 INFO    SenderThread:55280 [dir_watcher.py:finish():402] scan save: /Users/baeyeongmin/Desktop/workspace/dacon-2024-gbt-hackerton/wandb/run-20240927_121816-5tr1q16q/files/wandb-summary.json wandb-summary.json
2024-09-27 12:19:10,132 INFO    SenderThread:55280 [dir_watcher.py:finish():402] scan save: /Users/baeyeongmin/Desktop/workspace/dacon-2024-gbt-hackerton/wandb/run-20240927_121816-5tr1q16q/files/conda-environment.yaml conda-environment.yaml
2024-09-27 12:19:10,133 INFO    SenderThread:55280 [dir_watcher.py:finish():402] scan save: /Users/baeyeongmin/Desktop/workspace/dacon-2024-gbt-hackerton/wandb/run-20240927_121816-5tr1q16q/files/wandb-metadata.json wandb-metadata.json
2024-09-27 12:19:10,133 INFO    SenderThread:55280 [sender.py:transition_state():614] send defer: 10
2024-09-27 12:19:10,133 DEBUG   SenderThread:55280 [sender.py:send_request():406] send_request: poll_exit
2024-09-27 12:19:10,135 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: defer
2024-09-27 12:19:10,135 INFO    HandlerThread:55280 [handler.py:handle_request_defer():184] handle defer: 10
2024-09-27 12:19:10,135 DEBUG   SenderThread:55280 [sender.py:send_request():406] send_request: defer
2024-09-27 12:19:10,135 INFO    SenderThread:55280 [sender.py:send_request_defer():610] handle sender defer: 10
2024-09-27 12:19:10,135 INFO    SenderThread:55280 [file_pusher.py:finish():169] shutting down file pusher
2024-09-27 12:19:11,098 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: poll_exit
2024-09-27 12:19:11,098 DEBUG   SenderThread:55280 [sender.py:send_request():406] send_request: poll_exit
2024-09-27 12:19:11,280 INFO    wandb-upload_3:55280 [upload_job.py:push():130] Uploaded file /Users/baeyeongmin/Desktop/workspace/dacon-2024-gbt-hackerton/wandb/run-20240927_121816-5tr1q16q/files/wandb-summary.json
2024-09-27 12:19:11,380 INFO    wandb-upload_2:55280 [upload_job.py:push():130] Uploaded file /Users/baeyeongmin/Desktop/workspace/dacon-2024-gbt-hackerton/wandb/run-20240927_121816-5tr1q16q/files/config.yaml
2024-09-27 12:19:11,723 INFO    wandb-upload_4:55280 [upload_job.py:push():130] Uploaded file /Users/baeyeongmin/Desktop/workspace/dacon-2024-gbt-hackerton/wandb/run-20240927_121816-5tr1q16q/files/conda-environment.yaml
2024-09-27 12:19:11,937 INFO    wandb-upload_0:55280 [upload_job.py:push():130] Uploaded file /Users/baeyeongmin/Desktop/workspace/dacon-2024-gbt-hackerton/wandb/run-20240927_121816-5tr1q16q/files/requirements.txt
2024-09-27 12:19:12,104 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: poll_exit
2024-09-27 12:19:12,104 DEBUG   SenderThread:55280 [sender.py:send_request():406] send_request: poll_exit
2024-09-27 12:19:13,111 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: poll_exit
2024-09-27 12:19:13,111 DEBUG   SenderThread:55280 [sender.py:send_request():406] send_request: poll_exit
2024-09-27 12:19:13,626 INFO    wandb-upload_1:55280 [upload_job.py:push():130] Uploaded file /Users/baeyeongmin/Desktop/workspace/dacon-2024-gbt-hackerton/wandb/run-20240927_121816-5tr1q16q/files/output.log
2024-09-27 12:19:13,832 INFO    Thread-11 (_thread_body):55280 [sender.py:transition_state():614] send defer: 11
2024-09-27 12:19:13,833 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: defer
2024-09-27 12:19:13,833 INFO    HandlerThread:55280 [handler.py:handle_request_defer():184] handle defer: 11
2024-09-27 12:19:13,833 DEBUG   SenderThread:55280 [sender.py:send_request():406] send_request: defer
2024-09-27 12:19:13,833 INFO    SenderThread:55280 [sender.py:send_request_defer():610] handle sender defer: 11
2024-09-27 12:19:13,833 INFO    SenderThread:55280 [file_pusher.py:join():175] waiting for file pusher
2024-09-27 12:19:13,840 INFO    SenderThread:55280 [sender.py:transition_state():614] send defer: 12
2024-09-27 12:19:13,840 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: defer
2024-09-27 12:19:13,840 INFO    HandlerThread:55280 [handler.py:handle_request_defer():184] handle defer: 12
2024-09-27 12:19:13,840 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: status_report
2024-09-27 12:19:13,841 DEBUG   SenderThread:55280 [sender.py:send_request():406] send_request: defer
2024-09-27 12:19:13,841 INFO    SenderThread:55280 [sender.py:send_request_defer():610] handle sender defer: 12
2024-09-27 12:19:13,841 INFO    SenderThread:55280 [file_stream.py:finish():601] file stream finish called
2024-09-27 12:19:14,117 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: poll_exit
2024-09-27 12:19:14,127 INFO    SenderThread:55280 [file_stream.py:finish():605] file stream finish is done
2024-09-27 12:19:14,127 INFO    SenderThread:55280 [sender.py:transition_state():614] send defer: 13
2024-09-27 12:19:14,127 DEBUG   SenderThread:55280 [sender.py:send_request():406] send_request: poll_exit
2024-09-27 12:19:14,127 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: defer
2024-09-27 12:19:14,128 INFO    HandlerThread:55280 [handler.py:handle_request_defer():184] handle defer: 13
2024-09-27 12:19:14,129 DEBUG   SenderThread:55280 [sender.py:send_request():406] send_request: defer
2024-09-27 12:19:14,129 INFO    SenderThread:55280 [sender.py:send_request_defer():610] handle sender defer: 13
2024-09-27 12:19:14,129 INFO    SenderThread:55280 [sender.py:transition_state():614] send defer: 14
2024-09-27 12:19:14,129 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: defer
2024-09-27 12:19:14,130 DEBUG   SenderThread:55280 [sender.py:send():379] send: final
2024-09-27 12:19:14,130 INFO    HandlerThread:55280 [handler.py:handle_request_defer():184] handle defer: 14
2024-09-27 12:19:14,130 DEBUG   SenderThread:55280 [sender.py:send():379] send: footer
2024-09-27 12:19:14,130 DEBUG   SenderThread:55280 [sender.py:send_request():406] send_request: defer
2024-09-27 12:19:14,131 INFO    SenderThread:55280 [sender.py:send_request_defer():610] handle sender defer: 14
2024-09-27 12:19:14,131 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: poll_exit
2024-09-27 12:19:14,132 DEBUG   SenderThread:55280 [sender.py:send_request():406] send_request: poll_exit
2024-09-27 12:19:14,132 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: server_info
2024-09-27 12:19:14,133 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: poll_exit
2024-09-27 12:19:14,138 DEBUG   SenderThread:55280 [sender.py:send_request():406] send_request: server_info
2024-09-27 12:19:14,138 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: get_summary
2024-09-27 12:19:14,141 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: sampled_history
2024-09-27 12:19:14,141 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: internal_messages
2024-09-27 12:19:14,338 DEBUG   SenderThread:55280 [sender.py:send_request():406] send_request: poll_exit
2024-09-27 12:19:14,339 INFO    MainThread:55280 [wandb_run.py:_footer_history_summary_info():3991] rendering history
2024-09-27 12:19:14,339 INFO    MainThread:55280 [wandb_run.py:_footer_history_summary_info():4023] rendering summary
2024-09-27 12:19:14,344 INFO    MainThread:55280 [wandb_run.py:_footer_sync_info():3950] logging synced files
2024-09-27 12:19:14,361 DEBUG   HandlerThread:55280 [handler.py:handle_request():158] handle_request: shutdown
2024-09-27 12:19:14,361 INFO    HandlerThread:55280 [handler.py:finish():882] shutting down handler
2024-09-27 12:19:15,135 INFO    WriterThread:55280 [datastore.py:close():296] close: /Users/baeyeongmin/Desktop/workspace/dacon-2024-gbt-hackerton/wandb/run-20240927_121816-5tr1q16q/run-5tr1q16q.wandb
2024-09-27 12:19:15,341 INFO    SenderThread:55280 [sender.py:finish():1608] shutting down sender
2024-09-27 12:19:15,342 INFO    SenderThread:55280 [file_pusher.py:finish():169] shutting down file pusher
2024-09-27 12:19:15,342 INFO    SenderThread:55280 [file_pusher.py:join():175] waiting for file pusher
